workflows:
  build-android:
    name: Build AnyAPI WebView App
    max_build_duration: 15
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - focograal@gmail.com
