workflows:
  build-android:
    name: Build AnyAPI WebView App
    max_build_duration: 15
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - focograal@gmail.com
